
const wines = [
  {
    aging: "Crianza",
    bio: false,
    country: "Spain",
    name: "Viña Godeval",
    type: "White Wine",
    grapes:["Godello"],
    vintage: "2020",
    image: "/images/Viña-Godeval.png",
  },
  {
    aging: "Great Reserve",
    bio: false,
    country: "Germany",
    name: "Joel Gott",
    type: "White Wine",
    grapes:["Chardonnay"],
    vintage: "2013",
    image: "/images/Joel_Gott.png"
  },
  {
    aging: "Crianza",
    bio: true,
    country: "Spain",
    name: "Las Beatas",
    type: "Red Wine",
    grapes: ["Tempranillo", "Garnacha", "Graciano"],
    vintage: "2017",
    image: "/images/las-beatas.png"
  },
  {
    aging: "Crianza",
    bio: true,
    country: "Spain",
    name: "La Faraona",
    type: "Red Wine",
    grapes: ["Mencia"],
    vintage: "2018",
    image: "/images/La_Faraona.jpeg",
  },
  {
    aging: "Crianza",
    bio: false,
    country: "Spain",
    name: "Nussbaumer",
    type: "White Wine",
    grapes: ["Gewürztraminer"],
    vintage: "2021",
    image: "/images/Nussbaumer.png",
  },
  {
    aging: "Reserve",
    bio: false,
    country: "USA",
    name: "Ken Wright Cellars",
    type: "Red Wine",
    grapes: ["Pinot Noir"],
    vintage: "2016",
    image: "/images/Ken_Wright.png",
  },
  {
    aging: "Reserve",
    bio: false,
    country: "USA",
    name: "Aubert UV-SL",
    type: "Red Wine",
    grapes: ["Pinot Noir"],
    vintage: "2016",
    image: "/images/Aubert.png"
  },
  {
    aging: "Crianza",
    bio: true,
    country: "Italien",
    name: "San Filippo",
    type: "Red Wine",
    grapes: ["Sangiovese"],
    vintage: "2017",
    image: "/images/san_filippo.png",
  },
  {
    aging: "Crianza",
    bio: true,
    country: "USA",
    name: "Macayamas",
    type: "Red Wine",
    grapes: ["Cabernet Sauvignon"],
    vintage: "2015",
    image: "/images/mayacamas.png",
  },
  {
    aging: "Reserve",
    bio: false,
    country: "France",
    name: "Domaine de la Vieille Julienne",
    type: "Red Wine",
    grapes: ["Garnacha"],
    vintage: "2016",
    image: "/images/Vielle_Julienne.png",
  },
  {
    aging: "Crianza",
    bio: true,
    country: "USA",
    name: "Kistler",
    type: "White Wine",
    grapes: ["Chardonnay"],
    vintage: "2019",
    image: "/images/Kistler.png",
  },
  {
    aging: "Crianza",
    bio: true,
    country: "Argentina",
    name: "Los Chacayes",
    type: "Red Wine",
    grapes: ["Cabernet Sauvignon", "Malbec"],
    vintage: "2015",
    image: "/images/Los_Chacayes.png",
  },
  {
    aging: "Crianza",
    bio: false,
    country: "New Zeland",
    name: "Allan Scott",
    type: "White Wine",
    grapes: ["Sauvignon Blanc"],
    vintage: "2018",
    image: "/images/Allan_Scott.png",
  },
  {
    aging: "Reserve",
    bio: false,
    country: "France",
    name: "Clos de Beze",
    type: "Red Wine",
    grapes: ["Pinot Noir"],
    vintage: "2008",
    image: "/images/Clos-de-Beze.png",
  },
  {
    aging: "Crianza",
    bio: true,
    country: "Australia",
    name: "BIN 28 Kalimna",
    type: "Red Wine",
    grapes: ["Shiraz"],
    vintage: "2019",
    image: "/images/kalimna.png",
  },
  {
    aging: "Crianza",
    bio: true,
    country: "Chile",
    name: "Los Vascos",
    type: "White Wine",
    grapes: ["Sauvignon Blanc"],
    vintage: "2020",
    image: "/images/los_vascos.png",
  },
  {
    aging: "Reserve",
    bio: true,
    country: "France",
    name: "Trimbach",
    type: "White Wine",
    grapes: ["Riesling"],
    vintage: "2018",
    image: "/images/Trimbrach.png",
  },
  {
    aging: "Crianza",
    bio: true,
    country: "Italia",
    name: "Boscarelli",
    type: "Red Wine",
    grapes: ["Sangiovese"],
    vintage: "2016",
    image: "/images/boscarelli.png",
  },
  {
    aging: "Reserve",
    bio: false,
    country: "Argentina",
    name: "Bousquet",
    type: "Red Wine",
    grapes: [ "Cabernet Sauvignon","Malbec","Merlot","Syrah"],
    vintage: "2012",
    image: "/images/bousquet.png",
  },
  {
    aging: "Reserve",
    bio: false,
    country: "Australia",
    name: "Vasse Felix",
    type: "Red Wine",
    grapes: ["Cabernet Sauvignon","Merlot"],
    vintage: "2016",
    image: "/images/Vasse_Felix.png",
  },
  {
    aging: "Crianza",
    bio: true,
    country: "South Africa",
    name: "Southern Right",
    type: "White Wine",
    grapes: ["Sauvignon Blanc"],
    vintage: "2018",
    image: "/images/Southern-Rigth.png",
  },
  {
    aging: "Crianza",
    bio: true,
    country: "New Zealand",
    name: "Invivo",
    type: "White Wine",
    grapes: ["Sauvignon Blanc"],
    vintage: "2020",
    image: "/images/Invivo.png",
  },
  {
    aging: "Reserve",
    bio: false,
    country: "France",
    name: "Domaine de la Vieille Julienne",
    type: "Red Wine",
    grapes: ["Garnacha"],
    vintage: "2016",
    image: "/images/Vielle_Julienne.png",
  },
  {
    aging: "Crianza",
    bio: true,
    country: "USA",
    name: "Kistler",
    type: "White Wine",
    grapes: ["Chardonnay"],
    vintage: "2019",
    image: "/images/Kistler.webp",
  },
  {
    aging: "Crianza",
    bio: true,
    country: "Argentina",
    name: "De Sangre",
    type: "Red Wine",
    grapes: ["Malbec"],
    vintage: "2018",
    image: "/images/luigi-bosca.png",
  },
];

const Wine = require("../models/Wine.model");

// insertar en la BD
const mongoose = require("mongoose");

mongoose
  .connect("mongodb://localhost/wine-project")
  .then((response) => {
    console.log("conectados a la BD");

    return Wine.insertMany(wines);
  })
  .then((response) => {
    console.log("Wines agregados correctamente");

    mongoose.connection.close();
  })
  .catch((err) => {
    console.log(err);
  });

